local a = core.filter.add
a("render", { "position.x", "position.y", "drawReference" })
a("square", { "position.x", "position.y", "color.R", "color.G", "color.B" })
a("green", { "green" })
a("cyan", { "cyan" })
a("ember", { "ember" })
a("purple", { "purple" })
a("unwalkable", { "position.x", "position.y", "unwalkable" })
a("player", { "position.x", "position.y", "player" })
a("tiles", { "position.x", "position.y", "tileColor" })
a("persistent", { "persistent" })
a("nonPersistent", { "-persistent" })